# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Our Place in the Universe 
email: wafreema@syr.edu 
description: > # this means to ignore newlines until "baseurl:"
  Fall 2022, Syracuse University 
baseurl: "/ast101" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown  
kramdown:
  extensions: ["tables"]
#markdown: maruku

exclude: [.git]

collection:
  assignments:
    output: true
  notes:
    output: true
